// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    blockchain_contract
    (
        init => init
        upgrade => upgrade
        getRelease => get_release
        proposeRelease => propose_release
        approveRelease => approve_release
        rejectRelease => reject_release
        setRequiredApprovals => set_required_approvals
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
        getRequiredApprovals => required_approvals
        getSlots => slots
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
